homepage:
    pattern:  /
    defaults: { _controller: {{ namespace }}{{ appname }}Bundle:{{ controller }}:welcome }

{{ appname }}:
    pattern:  /{{ controller }}
    defaults: { _controller: {{ namespace }}{{ appname }}Bundle:{{ controller }}:index }
